env:
  CIRRUS_CLONE_SUBMODULES: true
  DEBIAN_FRONTEND: noninteractive
  LANG: C
  PGVERSION: 14

task:
  name: Windows
  windows_container:
    image: cirrusci/windowsservercore:cmake
  env:
    PATH: C:/tools/msys64/usr/bin;%PATH%
    HOME: .
    HAVE_IPV6_LOCALHOST: yes
  matrix:
    - env:
        MSYSTEM: MINGW64
    # - env:
    #     MSYSTEM: MINGW32
  setup_script:
    - choco install -y --no-progress msys2
    - sh -l -c "pacman --noconfirm -S --needed base-devel ${MINGW_PACKAGE_PREFIX}-gcc ${MINGW_PACKAGE_PREFIX}-libevent ${MINGW_PACKAGE_PREFIX}-openssl ${MINGW_PACKAGE_PREFIX}-postgresql autoconf automake libtool ${MINGW_PACKAGE_PREFIX}-python ${MINGW_PACKAGE_PREFIX}-python-pip zip"
    - sh -l -c 'pip install -r requirements.txt'
    - echo 127.0.0.1 localhost >> c:\Windows\System32\Drivers\etc\hosts
    - sh -l -c 'echo "127.0.0.1   localhost" >> /etc/hosts'
    - choco install -y --no-progress pandoc
  build_script:
    - sh -l -c "./autogen.sh"
    - sh -l -c "./configure --prefix=$HOME/install --enable-werror PANDOC=/c/programdata/chocolatey/bin/pandoc LDFLAGS='-L/mingw64/lib' LIBS='-liphlpapi -lssl -lcrypto' CPPFLAGS='-I/mingw64/include' PKG_CONFIG='pkg-config --static'"
    - sh -l -c "make -j4"
  test_script:
    - sh -l -c "make -j4 check CONCURRENCY=3"
    - sh -l -c "windres pgbouncer.exe"
  install_script:
    - sh -l -c "make -j4 install"
  dist_script:
    - sh -l -c "make -j4 zip"
  zip_artifacts:
    path: "pgbouncer-*.zip"
  always:
    configure_artifacts:
      path: "config.log"
      type: text/plain
