.\"     Title: pgbouncer
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.1 <http://docbook.sf.net/>
.\"      Date: 11/21/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "PGBOUNCER" "5" "11/21/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pgbouncer \- Lightweight connection pooler for PostgreSQL.
.SH "SYNOPSIS"
.sp
.RS 4
.nf
[databases]
db = ...
.fi
.RE
.sp
.RS 4
.nf
[pgbouncer]
...
.fi
.RE
.SH "DESCRIPTION"
Config file is in "ini" format. Section names are between " and ". Lines starting with ";" or "" are taken as comment and ignored. The characters ";" and "" are not recognized when they appear later in the line.
.sp
.SH "SECTION [PGBOUNCER]"
.SS "Generic settings"
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBlogfile\fR
.RS
Specifies log file. Log file is kept open so after rotation kill \-HUP or on console RELOAD; should be done.
.sp
Default: not set.
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBpidfile\fR
.RS
Specifies pid file. Without pidfile, the daemonization is not allowed.
.sp
Default: not set.
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBlisten_addr\fR
.RS
Specifies IPv4 address, where to listen for TCP connections. Or * meaning "listen on all addresses". When not set, only unix socket connections are allowed.
.sp
Default: not set
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBlisten_port\fR
.RS
On which port to listen on. Applies to both TCP and Unix sockets.
.sp
Default: 6000
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBunix_socket_dir\fR
.RS
Specifies location for Unix sockets. Applies to both listening socket and server connections. If set to empty string, Unix sockets are disabled.
.sp
Default: /tmp
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBauth_file\fR
.RS
Load user names and passwords from this file. File format used is same as for PostgreSQL pg_auth/pg_pwd file, so can be pointed directly to backend file.
.sp
Default: not set.
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBauth_type\fR
.RS
How to authenticate users.
.sp
.PP
md5
.RS 4
Use MD5\-based password check.
auth_file
may contain both md5\-encrypted or plain\-text passwords. Default.
.RE
.PP
crypt
.RS 4
Use crypt(3) based bassword check.
auth_file
must contain plain\-text passwords.
.RE
.PP
plain
.RS 4
Clear\-text password is sent over wire.
.RE
.PP
trust
.RS 4
No authentication is done. Username must still exists in
auth_file.
.RE
.PP
any
.RS 4
Like
trust
but username given is ignored. Requires that all databases have configured to log in as specific user.
.RE
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBpool_mode\fR
.RS
Specifies when server connection is tagged as reusable for other clients.
.sp
.PP
session
.RS 4
Server is released back to pool after client disconnects. Default.
.RE
.PP
transaction
.RS 4
Server is released back to pool after transaction finishes.
.RE
.PP
statement
.RS 4
Server is released back to pool after query finishes. Long transactions spanning multiple statements are disallowed in this mode.
.RE
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBmax_client_conn\fR
.RS
Maximum number of client connections allowed. When increased then the file descriptor limits should also be increased. Note that actual number of file descriptiors used is more that max_client_conn. Theoretical maximum used is:
.sp
.sp
.RS 4
.nf
max_client_conn + (max_pool_size * total_databases * total_users)
.fi
.RE
.sp
if each user connects under it's own username to server. If database user is specified in connect string (all users connect under same username), the theoretical maximum is:
.sp
.sp
.RS 4
.nf
max_client_conn + (max_pool_size * total_databases)
.fi
.RE
.sp
The theoretical maximum should be never reached, unless somebody deliberately crafts special load for it. Still, it means you should give fds liberately.
.sp
Search for ulimit in your favourite shell man page.
.sp
Default: 100
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBdefault_pool_size\fR
.RS
How many server connection to allow per user/database pair. Can be overrided in per\-database config.
.sp
Default: 20
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBserver_round_robin\fR
.RS
By default, pgbouncer reuses server connections in LIFO manner, so that few connections get the most load. This gives best performance if you have single server serving a database. But if there is TCP round\-robin behind a database IP then it's better if pgbouncer also uses connections in that manner, thus achieving uniform load.
.sp
Default: 0
.sp
.RE
.SS "Log settings"
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBlog_connections\fR
.RS
Log successful logins.
.sp
Default: 1
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBlog_disconnections\fR
.RS
Log disconnections with reasons.
.sp
Default: 1
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBlog_pooler_errors\fR
.RS
Log error messaged pooler sends to clients.
.sp
Default: 1
.sp
.RE
.SS "Console access control"
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBadmin_users\fR
.RS
List of users that are allowed to run all commands on console.
.sp
Default: empty
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBstats_users\fR
.RS
List of users that are allowed to run read\-only queries on console. Thats means all SHOW commands except SHOW FDS.
.sp
Default: empty.
.sp
.RE
.SS "Connection sanity checks, timeouts"
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBserver_reset_query\fR
.RS
Query send to server on connection release, before making it available to other clients. At that moment no transaction is in progress so it should not include ABORT or ROLLBACK.
.sp
Good choice for 8.2 and below is:
.sp
.sp
.RS 4
.nf
server_reset_query = RESET ALL; SET SESSION AUTHORIZATION DEFAULT;
.fi
.RE
.sp
for 8.3 and above its enough to do:
.sp
.sp
.RS 4
.nf
server_reset_query = DISCARD ALL;
.fi
.RE
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBserver_check_delay\fR
.RS
How long to keep released immidiately available, without running sanity\-check query on it. If 0 then the query is ran always.
.sp
Default: 30
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBserver_check_query\fR
.RS
Simple do\-nothing query to check if server connection is alive.
.sp
If empty string, then sanity checking is disabled.
.sp
Default: SELECT 1;
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBserver_lifetime\fR
.RS
Pooler tries to close server connections that are been connected longer than this.
.sp
Default: 3600
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBserver_idle_timeout\fR
.RS
If server connection has been idle more than this then there's too many connections in the pool and this one can be dropped.
.sp
Default: 600
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBserver_connect_timeout\fR
.RS
If connection and login wont finish in this time, the connection will be closed.
.sp
Default: 15
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBserver_login_retry\fR
.RS
If login failed, because of failure from connect() or authentication that pooler waits this much before retrying to connect.
.sp
Default: 15
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBclient_login_timeout\fR
.RS
If client connect but does not manage to login in this time, it will be disconnected. Mainly needed to avoid dead connections stalling SUSPEND and thus online restart.
.sp
Default: 60
.sp
.RE
.SS "Dangerous timeouts"
Setting following timeouts cause unexcpected errors.
.sp
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBquery_timeout\fR
.RS
Queries running longer than that are canceled. This should be used only with slightly smaller server\-side statement_timeout, to apply only for network problems.
.sp
Default: 0 (disabled)
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBclient_idle_timeout\fR
.RS
Client connections idling longer than that are closed. This should be larger then client\-side connection lifetime settings, to apply only for network problems.
.sp
Default: 0 (disabled)
.sp
.RE
.SS "Low\-level network settings"
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBpkt_buf\fR
.RS
Internal buffer size for packets. Affects size of TCP packets sent and general memory usage. Actual libpq packets can be larger than this so no need to set it large.
.sp
Default: 2048
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBtcp_defer_accept\fR
.RS
Details about following options shouldbe looked from man 7 tcp
.sp
Default: 45 on Linux, otherwise 0
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBtcp_socket_buffer\fR
.RS
Default: not set
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBtcp_keepalive\fR
.RS
Default: Not set
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBtcp_keepcnt\fR
.RS
Default: not set
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBtcp_keepidle\fR
.RS
Default: not set
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBtcp_keepintvl\fR
.RS
Default: not set
.sp
.RE
.SH "SECTION [DATABASES]"
This contains key=value pairs where key will be taken as database name and value as libpq\-connstring style list of key=value pairs. As actual libpq is not used, so not all features from libpq can be used (service=, quoting).
.sp
.SS "Location parameters"
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBdbname\fR
.RS
Destination database name.
.sp
Default: same as client\-side database name.
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBhost\fR
.RS
IP\-address to connect to.
.sp
Default: not set, meaning to use unix\-socket.
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBport\fR
.RS
Default: 5432
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBuser, password\fR
.RS
If user= is set, all connections to destination database will be done with that user, meaning that there will be only one pool for this database.
.sp
Otherwise pgbouncer tries to log into destination database with client username, meaning that there will be one pool per user.
.sp
.RE
.SS "Per\-database pool Size"
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBpool_size\fR
.RS
Set maximum size of pools for this database. If not set, the default_pool_size is used.
.sp
.RE
.SS "Extra parameters"
They allow setting default parameters on server connection.
.sp
Note that since version 1.1 PgBouncer tracks client changes for their values, so their use in pgbouncer.ini is deprecated now.
.sp
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBclient_encoding\fR
.RS
Ask specific client_encoding from server.
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBdatestyle\fR
.RS
Ask specific datestyle from server.
.sp
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBtimezone\fR
.RS
Ask specific timezone from server.
.sp
.RE
.SH "EXAMPLE"
.SS "Minimal config"
.sp
.RS 4
.nf
[databases]
template1 = host=127.0.0.1 dbname=template1
.fi
.RE
.sp
.RS 4
.nf
[pgbouncer]
pool_mode = session
listen_port = 6543
listen_addr = 127.0.0.1
auth_type = md5
auth_file = users.txt
logfile = pgbouncer.log
pidfile = pgbouncer.pid
admin_users = someuser
stats_users = stat_collector
.fi
.RE
.SS "Database defaults"
.sp
.RS 4
.nf
[databases]
.fi
.RE
.sp
.RS 4
.nf
; foodb over unix socket
foodb =
.fi
.RE
.sp
.RS 4
.nf
; redirect bardb to bazdb on localhost
bardb = host=127.0.0.1 dbname=bazdb
.fi
.RE
.sp
.RS 4
.nf
; acceess to dest database will go with single user
forcedb = host=127.0.0.1 port=300 user=baz password=foo client_encoding=UNICODE datestyle=ISO
.fi
.RE
.SH "SEE ALSO"
pgbouncer(1)
.sp
\fIhttps://developer.skype.com/SkypeGarage/DbProjects/PgBouncer\fR
.sp
